backup:
  enabled: true
  schedule: "0 1 * * *"
  image: "mongo:5"
  saveDays: "7"
  mongoUser: "user"
  mongoPass: "password"
  mongoHost: "host"
  storage: 
    type: "pvc" #pvc or s3
    pvc:
      size: "50Gi"
      storageClassName: "" #default
    s3:
      size: "50Gi"
      storageClassName: ""
      AWS_id: ""
      AWS_key: ""
